[functions.maintenance-provision-user-v2]
verify_jwt = true

[functions.tenant-invite-user-v2]
verify_jwt = true

[functions.send-account-credentials-email]
verify_jwt = true

[functions.sign-in-with-username]
verify_jwt = true
