import 'package:flutter_test/flutter_test.dart';
import 'package:v2mem_clinic/features/clinical_encounter/data/clinical_encounter_form_completion.dart';
import 'package:v2mem_clinic/features/clinical_encounter/data/clinical_encounter_form_section_id.dart';
import 'package:v2mem_clinic/features/clinical_encounter/models/clinical_encounter.dart';
import 'package:v2mem_clinic/features/clinical_encounter/models/clinical_treatment_approach.dart';

void main() {
  bool filled(String sectionId, {String chief = '', String note = ''}) {
    return ClinicalEncounterFormCompletion.isSectionFilled(
      sectionId,
      showPrivateNoteSection: true,
      chiefComplaint: chief,
      generalNotes: note,
      medications: '',
      complaintDuration: '',
      painLocation: '',
      painCharacter: '',
      activityRelation: '',
      previousTreatments: '',
      allergies: '',
      comorbidities: '',
      previousSurgeries: '',
      traumaHistory: false,
      nightPain: false,
      sportsSectionEnabled: false,
      sportBranch: '',
      amateurOrProfessional: '',
      trainingFrequency: '',
      patientExpectation: '',
      returnToSportGoal: '',
      returnToSportPlan: '',
      sportsRelated: false,
      inspection: '',
      palpation: '',
      rangeOfMotion: '',
      muscleStrength: '',
      stabilityTests: '',
      specialTests: '',
      neurovascularStatus: '',
      comparisonWithOtherSide: '',
      clinicalImpression: '',
      imagingSummary: '',
      imagingDoctorComment: '',
      attachedFileNote: '',
      preliminaryDiagnosis: '',
      finalDiagnosis: '',
      differentialDiagnosis: '',
      icdCode: '',
      planTitle: '',
      conservativeTreatment: '',
      medicationNotes: '',
      injectionOrProcedurePlan: '',
      orthosisNotes: '',
      surgeryRecommendation: '',
      treatmentApproach: null,
      physiotherapyReferral: false,
      exerciseRecommendation: '',
      imagingRequest: '',
      controlDate: null,
      status: ClinicalEncounterStatus.taslak,
      patientInformationNote: '',
      warningNotes: '',
      internalDoctorNote: '',
    );
  }

  test('complaint section filled when chief complaint has text', () {
    expect(
      filled(ClinicalEncounterFormSectionId.complaint, chief: 'Diz ağrısı'),
      isTrue,
    );
    expect(filled(ClinicalEncounterFormSectionId.complaint), isFalse);
  });

  test('diagnosis section filled when icd code present', () {
    expect(
      ClinicalEncounterFormCompletion.isSectionFilled(
        ClinicalEncounterFormSectionId.diagnosis,
        showPrivateNoteSection: true,
        chiefComplaint: '',
        generalNotes: '',
        medications: '',
        complaintDuration: '',
        painLocation: '',
        painCharacter: '',
        activityRelation: '',
        previousTreatments: '',
        allergies: '',
        comorbidities: '',
        previousSurgeries: '',
        traumaHistory: false,
        nightPain: false,
        sportsSectionEnabled: false,
        sportBranch: '',
        amateurOrProfessional: '',
        trainingFrequency: '',
        patientExpectation: '',
        returnToSportGoal: '',
        returnToSportPlan: '',
        sportsRelated: false,
        inspection: '',
        palpation: '',
        rangeOfMotion: '',
        muscleStrength: '',
        stabilityTests: '',
        specialTests: '',
        neurovascularStatus: '',
        comparisonWithOtherSide: '',
        clinicalImpression: '',
        imagingSummary: '',
        imagingDoctorComment: '',
        attachedFileNote: '',
        preliminaryDiagnosis: '',
        finalDiagnosis: '',
        differentialDiagnosis: '',
        icdCode: 'M23.2',
        planTitle: '',
        conservativeTreatment: '',
        medicationNotes: '',
        injectionOrProcedurePlan: '',
        orthosisNotes: '',
        surgeryRecommendation: '',
        treatmentApproach: null,
        physiotherapyReferral: false,
        exerciseRecommendation: '',
        imagingRequest: '',
        controlDate: null,
        status: ClinicalEncounterStatus.taslak,
        patientInformationNote: '',
        warningNotes: '',
        internalDoctorNote: '',
      ),
      isTrue,
    );
  });

  test('private note section only when note text exists', () {
    expect(
      filled(ClinicalEncounterFormSectionId.privateNote, note: 'gizli'),
      isFalse,
    );
    expect(
      ClinicalEncounterFormCompletion.isSectionFilled(
        ClinicalEncounterFormSectionId.privateNote,
        showPrivateNoteSection: true,
        chiefComplaint: '',
        generalNotes: '',
        medications: '',
        complaintDuration: '',
        painLocation: '',
        painCharacter: '',
        activityRelation: '',
        previousTreatments: '',
        allergies: '',
        comorbidities: '',
        previousSurgeries: '',
        traumaHistory: false,
        nightPain: false,
        sportsSectionEnabled: false,
        sportBranch: '',
        amateurOrProfessional: '',
        trainingFrequency: '',
        patientExpectation: '',
        returnToSportGoal: '',
        returnToSportPlan: '',
        sportsRelated: false,
        inspection: '',
        palpation: '',
        rangeOfMotion: '',
        muscleStrength: '',
        stabilityTests: '',
        specialTests: '',
        neurovascularStatus: '',
        comparisonWithOtherSide: '',
        clinicalImpression: '',
        imagingSummary: '',
        imagingDoctorComment: '',
        attachedFileNote: '',
        preliminaryDiagnosis: '',
        finalDiagnosis: '',
        differentialDiagnosis: '',
        icdCode: '',
        planTitle: '',
        conservativeTreatment: '',
        medicationNotes: '',
        injectionOrProcedurePlan: '',
        orthosisNotes: '',
        surgeryRecommendation: '',
        treatmentApproach: null,
        physiotherapyReferral: false,
        exerciseRecommendation: '',
        imagingRequest: '',
        controlDate: null,
        status: ClinicalEncounterStatus.taslak,
        patientInformationNote: '',
        warningNotes: '',
        internalDoctorNote: 'Doktor notu',
      ),
      isTrue,
    );
  });

  test('treatment section filled when approach selected', () {
    expect(
      ClinicalEncounterFormCompletion.isSectionFilled(
        ClinicalEncounterFormSectionId.treatment,
        showPrivateNoteSection: false,
        chiefComplaint: '',
        generalNotes: '',
        medications: '',
        complaintDuration: '',
        painLocation: '',
        painCharacter: '',
        activityRelation: '',
        previousTreatments: '',
        allergies: '',
        comorbidities: '',
        previousSurgeries: '',
        traumaHistory: false,
        nightPain: false,
        sportsSectionEnabled: false,
        sportBranch: '',
        amateurOrProfessional: '',
        trainingFrequency: '',
        patientExpectation: '',
        returnToSportGoal: '',
        returnToSportPlan: '',
        sportsRelated: false,
        inspection: '',
        palpation: '',
        rangeOfMotion: '',
        muscleStrength: '',
        stabilityTests: '',
        specialTests: '',
        neurovascularStatus: '',
        comparisonWithOtherSide: '',
        clinicalImpression: '',
        imagingSummary: '',
        imagingDoctorComment: '',
        attachedFileNote: '',
        preliminaryDiagnosis: '',
        finalDiagnosis: '',
        differentialDiagnosis: '',
        icdCode: '',
        planTitle: '',
        conservativeTreatment: '',
        medicationNotes: '',
        injectionOrProcedurePlan: '',
        orthosisNotes: '',
        surgeryRecommendation: '',
        treatmentApproach: ClinicalTreatmentApproach.conservative,
        physiotherapyReferral: false,
        exerciseRecommendation: '',
        imagingRequest: '',
        controlDate: null,
        status: ClinicalEncounterStatus.taslak,
        patientInformationNote: '',
        warningNotes: '',
        internalDoctorNote: '',
      ),
      isTrue,
    );
  });
}
